<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>OMNeT++ Simulation Library: cException Class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
<link href="tabs.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.5 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li><a href="dirs.html"><span>Directories</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
<h1>cException Class Reference<br>
<small>
[<a class="el" href="group__SimSupport.html">Utility classes</a>]</small>
</h1><!-- doxytag: class="cException" --><code>#include &lt;<a class="el" href="cexception_8h-source.html">cexception.h</a>&gt;</code>
<p>
<div class="dynheader">
Inheritance diagram for cException:</div>
<div class="dynsection">

<p><center><img src="classcException.png" usemap="#cException_map" border="0" alt=""></center>
<map name="cException_map">
<area href="classcDeleteModuleException.html" alt="cDeleteModuleException" shape="rect" coords="0,56,152,80">
<area href="classcRuntimeError.html" alt="cRuntimeError" shape="rect" coords="162,56,314,80">
<area href="classcStackCleanupException.html" alt="cStackCleanupException" shape="rect" coords="324,56,476,80">
<area href="classcTerminationException.html" alt="cTerminationException" shape="rect" coords="486,56,638,80">
</map>
</div>

<p>
<a href="classcException-members.html">List of all members.</a><hr><a name="_details"></a><h2>Detailed Description</h2>
Exception class. <table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td colspan="2"><div class="groupHeader">Constructors, destructor</div></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#e37c072e7711457f2baadd31e0dc99b2">cException</a> (OppErrorCode errcode,...)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#7f7fcd4d98b0c32fb9b85030a90f3c54">cException</a> (const char *msg,...)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#49e99763b394cd114aef2dc543958472">cException</a> (const <a class="el" href="classcObject.html">cObject</a> *where, OppErrorCode errcode,...)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#9661042c3ba62741d8afde2238719fbf">cException</a> (const <a class="el" href="classcObject.html">cObject</a> *where, const char *msg,...)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#20bdf9ba513c144630d8b809e95fda1c">cException</a> (const <a class="el" href="classcException.html">cException</a> &amp;)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual <a class="el" href="classcException.html">cException</a> *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#7aae9b928c595645f2918a897eb14c2b">dup</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#616a152a7a238d75cd1f93ece2e0ce15">~cException</a> ()  throw ()</td></tr>

<tr><td colspan="2"><div class="groupHeader">Updating the exception message</div></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#fad7de0aaeadf1be7aac3174ce67a73f">setMessage</a> (const char *txt)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#668b1549d73a30b9ff3f2d4e615c3de0">prependMessage</a> (const char *txt)</td></tr>

<tr><td colspan="2"><div class="groupHeader">Getting exception info</div></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#e94e8963aaae31fc8609986128d38d52">isError</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#66e376301220fd82c9da9bdeab664365">getErrorCode</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#ec27fc122c18bc5432fb798188bb0af7">what</a> () const   throw ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual std::string&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#6d6e6a3f46967732ed62cc19a2805169">getFormattedMessage</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#14bc3aa629707ee37a10d724b8fa451f">getSimulationStage</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual eventnumber_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#a6a0dcd4d786e12318ef826867087353">getEventNumber</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual simtime_t&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#f4d9f0a1904d84fb89d8a20977a974af">getSimtime</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#5222f000f4d39b905ce471cf8ee4ded0">hasContext</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#e05fe03bbe292c5c2907e08da8f62e30">getContextClassName</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual const char *&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#42d56ca373f6025d0517cc081523b769">getContextFullPath</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">virtual int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#65b5c33d50a8a76db2eba3b6868821a3">getModuleID</a> () const </td></tr>

<tr><td colspan="2"><br><h2>Protected Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classcException.html#3dc884d1fd5a29cbb7ef2c0fa7851717">init</a> (const <a class="el" href="classcObject.html">cObject</a> *obj, OppErrorCode errorcode, const char *fmt, va_list va)</td></tr>

</table>
<hr><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" name="e37c072e7711457f2baadd31e0dc99b2"></a><!-- doxytag: member="cException::cException" ref="e37c072e7711457f2baadd31e0dc99b2" args="(OppErrorCode errcode,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException           </td>
          <td>(</td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Error is identified by an error code, and the message comes from a string table. 
<p>
The error string may expect printf-like arguments (s, d) which also have to be passed to the constructor. 
</div>
</div><p>
<a class="anchor" name="7f7fcd4d98b0c32fb9b85030a90f3c54"></a><!-- doxytag: member="cException::cException" ref="7f7fcd4d98b0c32fb9b85030a90f3c54" args="(const char *msg,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException           </td>
          <td>(</td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>msg</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
To be called like printf(). 
<p>
The error code is set to eCUSTOM. 
</div>
</div><p>
<a class="anchor" name="49e99763b394cd114aef2dc543958472"></a><!-- doxytag: member="cException::cException" ref="49e99763b394cd114aef2dc543958472" args="(const cObject *where, OppErrorCode errcode,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>where</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Error is identified by an error code, and the message comes from a string table. 
<p>
The error string may expect printf-like arguments (s, d) which also have to be passed to the constructor. The 1st arg is the object where the error occurred: its class and object name will be prepended to the message like this: "(cArray)arr". 
</div>
</div><p>
<a class="anchor" name="9661042c3ba62741d8afde2238719fbf"></a><!-- doxytag: member="cException::cException" ref="9661042c3ba62741d8afde2238719fbf" args="(const cObject *where, const char *msg,...)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>where</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>msg</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&nbsp;</td>
          <td class="paramname"> <em>...</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
To be called like printf(). 
<p>
The error code is set to eCUSTOM. The 1st arg is the object where the error occurred: its class and object name will be prepended to the message like this: "(cArray)arr". 
</div>
</div><p>
<a class="anchor" name="20bdf9ba513c144630d8b809e95fda1c"></a><!-- doxytag: member="cException::cException" ref="20bdf9ba513c144630d8b809e95fda1c" args="(const cException &amp;)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">cException::cException           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcException.html">cException</a> &amp;&nbsp;</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
We unfortunately need to copy exception objects when handing them back from an activity(). 
<p>

</div>
</div><p>
<a class="anchor" name="616a152a7a238d75cd1f93ece2e0ce15"></a><!-- doxytag: member="cException::~cException" ref="616a152a7a238d75cd1f93ece2e0ce15" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual cException::~cException           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%">  throw ()<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Destructor. 
<p>

</div>
</div><p>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="3dc884d1fd5a29cbb7ef2c0fa7851717"></a><!-- doxytag: member="cException::init" ref="3dc884d1fd5a29cbb7ef2c0fa7851717" args="(const cObject *obj, OppErrorCode errorcode, const char *fmt, va_list va)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void cException::init           </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classcObject.html">cObject</a> *&nbsp;</td>
          <td class="paramname"> <em>obj</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">OppErrorCode&nbsp;</td>
          <td class="paramname"> <em>errorcode</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>fmt</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">va_list&nbsp;</td>
          <td class="paramname"> <em>va</em></td><td>&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td><td width="100%"><code> [protected]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Helper function for constructors: assembles and stores the message text. 
<p>
If the first arg is non-NULL, the message text will be prepended (if needed) with the object type and name, like this: "(cArray)array: ..." 
</div>
</div><p>
<a class="anchor" name="7aae9b928c595645f2918a897eb14c2b"></a><!-- doxytag: member="cException::dup" ref="7aae9b928c595645f2918a897eb14c2b" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual <a class="el" href="classcException.html">cException</a>* cException::dup           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Virtual copy constructor. 
<p>
We unfortunately need to copy exception objects when handing them back from an activity(). 
<p>Reimplemented in <a class="el" href="classcTerminationException.html#3cc34be98273933d33c17328b9c0f5e6">cTerminationException</a>, <a class="el" href="classcRuntimeError.html#6d34e0bf66e83e7c209bb72df3b816f8">cRuntimeError</a>, <a class="el" href="classcDeleteModuleException.html#66df169476c0f09ae5a66bd3616c6143">cDeleteModuleException</a>, and <a class="el" href="classcStackCleanupException.html#6106d0f66dee0d823e1f6f4868c9ea65">cStackCleanupException</a>.</p>

</div>
</div><p>
<a class="anchor" name="fad7de0aaeadf1be7aac3174ce67a73f"></a><!-- doxytag: member="cException::setMessage" ref="fad7de0aaeadf1be7aac3174ce67a73f" args="(const char *txt)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual void cException::setMessage           </td>
          <td>(</td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>txt</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Overwrites the message text with the given one. 
<p>

</div>
</div><p>
<a class="anchor" name="668b1549d73a30b9ff3f2d4e615c3de0"></a><!-- doxytag: member="cException::prependMessage" ref="668b1549d73a30b9ff3f2d4e615c3de0" args="(const char *txt)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual void cException::prependMessage           </td>
          <td>(</td>
          <td class="paramtype">const char *&nbsp;</td>
          <td class="paramname"> <em>txt</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"><code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Prefixes the message with the given text and a colon. 
<p>

</div>
</div><p>
<a class="anchor" name="e94e8963aaae31fc8609986128d38d52"></a><!-- doxytag: member="cException::isError" ref="e94e8963aaae31fc8609986128d38d52" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool cException::isError           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Whether the exception represents an error or a normal (non-error) terminating condition (e.g. 
<p>
"Simulation completed"). 
<p>Reimplemented in <a class="el" href="classcTerminationException.html#800ea3ac1413f70600cb9118eb7c1003">cTerminationException</a>, <a class="el" href="classcDeleteModuleException.html#69946544e7468f833e5526a4478746a4">cDeleteModuleException</a>, and <a class="el" href="classcStackCleanupException.html#b7728cfc9eb1e9d507f9ddbc7163f580">cStackCleanupException</a>.</p>

</div>
</div><p>
<a class="anchor" name="66e376301220fd82c9da9bdeab664365"></a><!-- doxytag: member="cException::getErrorCode" ref="66e376301220fd82c9da9bdeab664365" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual int cException::getErrorCode           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the error code. 
<p>

</div>
</div><p>
<a class="anchor" name="ec27fc122c18bc5432fb798188bb0af7"></a><!-- doxytag: member="cException::what" ref="ec27fc122c18bc5432fb798188bb0af7" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual const char* cException::what           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const  throw ()<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the text of the error. 
<p>
Redefined from std::exception. 
</div>
</div><p>
<a class="anchor" name="6d6e6a3f46967732ed62cc19a2805169"></a><!-- doxytag: member="cException::getFormattedMessage" ref="6d6e6a3f46967732ed62cc19a2805169" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual std::string cException::getFormattedMessage           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns a formatted message that includes the "Error" word, context information, the event number and simulation time if available and relevant, in addition to the exception message (<a class="el" href="classcException.html#ec27fc122c18bc5432fb798188bb0af7" title="Returns the text of the error.">what()</a>). 
<p>

</div>
</div><p>
<a class="anchor" name="14bc3aa629707ee37a10d724b8fa451f"></a><!-- doxytag: member="cException::getSimulationStage" ref="14bc3aa629707ee37a10d724b8fa451f" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual int cException::getSimulationStage           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns in which stage of the simulation the exception object was created: during network building (CTX_BUILD), network initialization (CTX_INITIALIZE), simulation execution (CTX_EVENT), finalization (CTX_FINISH), or network cleanup (CTX_CLEANUP). 
<p>

</div>
</div><p>
<a class="anchor" name="a6a0dcd4d786e12318ef826867087353"></a><!-- doxytag: member="cException::getEventNumber" ref="a6a0dcd4d786e12318ef826867087353" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual eventnumber_t cException::getEventNumber           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the event number at the creation of the exception object. 
<p>

</div>
</div><p>
<a class="anchor" name="f4d9f0a1904d84fb89d8a20977a974af"></a><!-- doxytag: member="cException::getSimtime" ref="f4d9f0a1904d84fb89d8a20977a974af" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual simtime_t cException::getSimtime           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the simulation time at the creation of the exception object. 
<p>

</div>
</div><p>
<a class="anchor" name="5222f000f4d39b905ce471cf8ee4ded0"></a><!-- doxytag: member="cException::hasContext" ref="5222f000f4d39b905ce471cf8ee4ded0" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool cException::hasContext           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns true if the exception has "context info", that is, it occurred within a known module or channel. 
<p>
<a class="el" href="classcException.html#e05fe03bbe292c5c2907e08da8f62e30" title="Returns the class name (NED type name) of the context where the exception occurred...">getContextClassName()</a>, <a class="el" href="classcException.html#42d56ca373f6025d0517cc081523b769" title="Returns the full path of the context where the exception occurred.">getContextFullPath()</a> and <a class="el" href="classcException.html#65b5c33d50a8a76db2eba3b6868821a3" title="Returns the ID of the module where the exception occurred, or -1 if it was not inside...">getModuleID()</a> may only be called if this method returns true. 
</div>
</div><p>
<a class="anchor" name="e05fe03bbe292c5c2907e08da8f62e30"></a><!-- doxytag: member="cException::getContextClassName" ref="e05fe03bbe292c5c2907e08da8f62e30" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual const char* cException::getContextClassName           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the class name (NED type name) of the context where the exception occurred. 
<p>

</div>
</div><p>
<a class="anchor" name="42d56ca373f6025d0517cc081523b769"></a><!-- doxytag: member="cException::getContextFullPath" ref="42d56ca373f6025d0517cc081523b769" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual const char* cException::getContextFullPath           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the full path of the context where the exception occurred. 
<p>

</div>
</div><p>
<a class="anchor" name="65b5c33d50a8a76db2eba3b6868821a3"></a><!-- doxytag: member="cException::getModuleID" ref="65b5c33d50a8a76db2eba3b6868821a3" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">virtual int cException::getModuleID           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td width="100%"> const<code> [inline, virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the ID of the module where the exception occurred, or -1 if it was not inside a module. 
<p>
The module may not exist any more when the exception is caught (ie. if the exception occurs during network setup, the network is cleaned up immediately). 
</div>
</div><p>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="cexception_8h-source.html">cexception.h</a></ul>
</div>
<hr size="1"><address style="text-align: right;"><small>Generated on Tue Mar 27 11:22:11 2012 for OMNeT++ Simulation Library by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.5 </small></address>
</body>
</html>
